<div class="container">
    <form class="form-horizontal" action="<?= $block->getUrl('test/front/save'); ?>" method='post' enctype="multipart/form-data">
        <div class="form-group">
            <label class="control-label col-sm-2" for="email">name:</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="name" name="name">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="email">image:</label>
            <div class="col-sm-10">
                <input type="file" class="form-control" id="img" name="image">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
        </div>
    </form>
</div>