<?php

$objectManager 	=  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager 	= $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$mediaurl 		= $storeManager->getStore()->getBaseUrl
(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

$urlInterface 	= $objectManager->get('Magento\Framework\UrlInterface');

//$imageuploadurl = $urlInterface->getUrl('selection/selection/imageupload');

//$questionData 	= $block->getKey();

 echo "Hello";
 
 
 
 ?>
 <div class="custom_form">
	<fieldset class="fieldset admin__fieldset fieldset-wide">
		<div class="admin__field field questionfield_box">
			<label class="label admin__field-label">
				<span>Question</span>
			</label>
			<div class="admin__field-control control">
				<input type="text" class="input-text admin__control-text questionfield">
				<input type="hidden" class="idfield">
				<input type="hidden" class="editflagfield">
			</div>		 
		</div>
		<div class="admin__field field optionsfield_box">
			<label class="label admin__field-label">
				<span>Options</span>
			</label>
			<div class="admin__field-control control">
				<select class="select admin__control-select optionsfield">
					<option value="">Choose Option</option>
					<option value="1">Select</option>
					<option value="2">Checkbox</option>
					<option value="3">Radio</option>
					<option value="4">Image</option>
				</select>
			</div>		
		</div>
		<div class="admin__field field displaynone choice_box">
			<div class="choicestablewrapper">
				<table class="choicestable">
					<tr>
						<th>Key</th>
						<th>Value</th>
						<th><button class="choicesbtn">Add Choice</button></th>
					</tr>
				</table>
			</div>
		</div>
		<div class="admin__field field">
			<label class="label admin__field-label">
				<span></span>
			</label>
			<div class="admin__field-control control">
				<input type="button" value="ADD" class="addfield">
			</div>		
		</div>
	</fieldset>
</div>

<script>
require(['jquery', 'jquery/ui'], function($){
  $(document).ready( function() {
    $('.choice_box').hide();
    $('.optionsfield').change(function(){
			var value = $(this).val();
			optiontoggle(value);
		})
		
		function optiontoggle(value, disableclick=''){
                $('.choicesrow').remove();
                
                if(value==''){
                	$('.choice_box').hide();
                }else{
                	$('.choice_box').show();
                	if(disableclick=='') $('.choicesbtn').click();
                }
		}
  });
});
   
</script>


