<?php
$objectManager 	=  \Magento\Framework\App\ObjectManager::getInstance();
 
$storeManager 	= $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$mediaurl 		= $storeManager->getStore()->getBaseUrl
(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

$urlInterface 	= $objectManager->get('Magento\Framework\UrlInterface');

$imageuploadurl = $urlInterface->getUrl('selection/selection/imageupload');

$questionData 	= $block->getKey();

$placeholderimg = $this->getViewFileUrl('Itf_Selection::images/placeholder.jpg');

?>
<div class="custom_form">
	<fieldset class="fieldset admin__fieldset fieldset-wide">
		<div class="admin__field field questionfield_box">
			<label class="label admin__field-label">
				<span>Question</span>
			</label>
			<div class="admin__field-control control">
				<input type="text" class="input-text admin__control-text questionfield">
				<input type="hidden" class="idfield">
				<input type="hidden" class="editflagfield">
			</div>		 
		</div>
		<div class="admin__field field optionsfield_box">
			<label class="label admin__field-label">
				<span>Options</span>
			</label>
			<div class="admin__field-control control">
				<select class="select admin__control-select optionsfield">
					<option value="">Choose Option</option>
					<option value="1">Select</option>
					<option value="2">Checkbox</option>
					<option value="3">Radio</option>
					<option value="4">Image</option>
				</select>
			</div>		
		</div>
		<div class="admin__field field displaynone choice_box">
			<div class="choicestablewrapper">
				<table class="choicestable">
					<tr>
						<th>Key</th>
						<th>Value</th>
						<th><button class="choicesbtn">Add Choice</button></th>
					</tr>
				</table>
			</div>
		</div>
		<div class="admin__field field">
			<label class="label admin__field-label">
				<span></span>
			</label>
			<div class="admin__field-control control">
				<input type="button" value="ADD" class="addfield">
			</div>		
		</div>
	</fieldset>
</div>
<script>
	require(['jquery'], function($){
		
		var mediaurl 		= 	'<?php echo $mediaurl; ?>';
		var qd 				= 	'<?php echo $questionData; ?>';
		var filepath 		= 	mediaurl+'selection/question/';
		var questioncount	=	1;
		
		$(function(){
			
			if(qd!=''){
				var qdsplit1 = qd.split('@_@');
				$.each(qdsplit1, function(i, v){
					var qdsplit2 = v.split('@@@');
					var id 					= (qdsplit2[0]) ? qdsplit2[0] : '';
					var questionfield 		= (qdsplit2[1]) ? qdsplit2[1] : '';
					var optionsfield 		= (qdsplit2[2]) ? qdsplit2[2] : '';
					var choicefield			= (qdsplit2[3]) ? $.parseJSON(qdsplit2[3]) : '';
					
					var optionsdata = '';
					if(optionsfield=='1') optionsdata = 'Select';
					else if(optionsfield=='2') optionsdata = 'Checkbox';
					else if(optionsfield=='3') optionsdata = 'Radio';
					else if(optionsfield=='4') optionsdata = 'Image';
					
					fieldgeneration(questionfield, optionsdata, optionsfield, choicefield, id)
				})
			}
		})
		
		// Toggle Options
		
		$('.optionsfield').change(function(){
			var value = $(this).val();
			optiontoggle(value);
		})
		
		function optiontoggle(value, disableclick=''){
			$('.choicesrow').remove();
			
			if(value==''){
				$('.choice_box').hide();
			}else{
				$('.choice_box').show();
				if(disableclick=='') $('.choicesbtn').click();
			}
		}
		
		$('.choicesbtn').click(function(){
			choicesfield();
		})
		
		function choicesfield(key='', value='', image=''){
			var image	= 	(image=='') ? '<?php echo $placeholderimg; ?>' : image;
			var options = 	$('.optionsfield').val();
			
			var data 	= 	'<tr class="choicesrow">\
								<td><input type="text" class="input-text admin__control-text choiceskey" value="'+key+'"></td>';
							
			if(options==4){
				data	+=		'<td>\
									<img src="'+image+'" class="choicesplaceholderimage" width="30px">\
									<input type="file" class="displaynone choicesimage">\
									<input type="hidden" class="choicesvalue" value="'+value+'">\
								</td>';
			}else{
				data	+=		'<td><input type="text" class="input-text admin__control-text choicesvalue" value="'+value+'"></td>';
			}
			
			data		+=	'	<td><button class="choicesdelete">Delete</button></td>\
							</tr>';
			
			$('.choicestable').append(data);
		}
		
		$(document).on('click', '.choicesdelete', function(){
			$(this).parent().parent().remove();
		})
		
		// Image Upload
		
		$(document).on('click', '.choicesplaceholderimage', function(){
			$(this).parent().find('.choicesimage').click();
		})
		
		$(document).on('change', '.choicesimage', function(){
			var _this		= $(this);
			var supportExt 	= ["png", "jpg", "jpeg"];
			var name 		= _this.val();
			var ext 		= name.split('.').pop().toLowerCase();
			
			if($.inArray(ext, supportExt) !== -1){			
				var form_data 	= new FormData();
				form_data.append("image", $(this)[0].files[0]);
				form_data.append("id", '');
				form_data.append("form_key", $('input[name="form_key"]').val());
				$.ajax({
					url 		: 	'<?php echo $imageuploadurl; ?>',
					type 		: 	'post',
					data 		: 	form_data,
					dataType 	: 	'json',
					contentType	: 	false,
					processData	: 	false,
					success 	: 	function(data){ 
										if(data && data.status==1){
											_this.parent().find('.choicesplaceholderimage').attr('src', filepath+data.file);
											_this.parent().find('.choicesvalue').val(data.file);
										}
									}
				})
			}else{
				_this.val('');
				alert('Supported file format are png, jpg, jpeg');
			}
		})
		
		// Add Action
		
		$('.addfield').click(function(){
			var validation			= true;
			var idfield 			= $('.idfield').val();
			var questionfield 		= $('.questionfield').val();
			var optionsfieldtext 	= $('.optionsfield option:selected').text();
			var optionsfield 		= $('.optionsfield option:selected').val();
			var choicefield			= [];
			
			$('.custom-error').remove();
				
			if(questionfield==''){
				$('.questionfield').parent().append('<label class="mage-error custom-error">This is a required field.</label>');
				validation = false;
			}
			
			if(optionsfield==''){
				$('.optionsfield').parent().append('<label class="mage-error custom-error">This is a required field.</label>');
				validation = false;
			}
			
			$(document).find('.choicesrow').each(function(){
				var key 	= $(this).find('.choiceskey').val();
				var value 	= $(this).find('.choicesvalue').val();
				
				if(key==''){
					$(this).find('.choiceskey').parent().append('<label class="mage-error custom-error">This is a required field.</label>');
					validation = false;
				}
				
				if(value==''){
					$(this).find('.choicesvalue').parent().append('<label class="mage-error custom-error">This is a required field.</label>');
					validation = false;
				}
				
				choicefield.push({'key' : key, 'value' : value});
			})		
			
			if(validation==false) return false;
			
			fieldgeneration(questionfield, optionsfieldtext, optionsfield, choicefield, idfield);
		})
		
		function fieldgeneration(questionfield, optionsfieldtext, optionsfield, choicefield, id=''){
			
			var editflag 				= $('.editflagfield').val();
			var questioncountduplicate 	= questioncount;
			if(editflag!=''){
				$(document).find('#custom_form_data_'+editflag).remove();
				$(document).find('.custom_form_data_hidden_'+editflag).remove();
				questioncount = editflag;
			} 
			
			if(!$(document).find('.custom_form_wrapper').length){
				$('.custom_form').parent().append('<div class="custom_form_wrapper"></div>');
			}
			
			var choicecount 		= 0;
			var choicesection 		= '';
			var choicehiddensection = '';
			$(choicefield).each(function(i, v){
				if(optionsfield==4){
					var value = '<img src="'+filepath+v.value+'" width="50px">';
				}else{
					var value = v.value;
				}
				
				choicesection 	+= 	'<tr>\
										<td>'+v.key+'</td>\
										<td>'+value+'</td>\
									</tr>';
				
				choicehiddensection += 	'<input type="hidden" class="keyhidden" value="'+v.key+'" name="questiondata['+questioncount+'][choices]['+choicecount+'][key]">\
										<input type="hidden" class="valuehidden" value="'+v.value+'" name="questiondata['+questioncount+'][choices]['+choicecount+'][value]">';
										
				choicecount++;
			})
			
			var data = 	'<div class="custom_form_data" id="custom_form_data_'+questioncount+'">\
							<h2>'+questionfield+' ('+optionsfieldtext+')  <a href="javascript:void(0);" class="editfield" data-id="'+questioncount+'">Edit</a> <span>/</span> <a href="javascript:void(0);" class="removefield" data-id="'+questioncount+'">Remove</a></h2>\
							<div class="choicesection">\
								<table>\
									<tr>\
										<th>Key</th>\
										<th>Value</th>\
									</tr>\
									'+choicesection+'\
								</table>\
							</div>\
						</div>';
			
			if(editflag!=''){
				var appendcount = questioncount-1;
				(appendcount==0) ? $(document).find('.custom_form_wrapper').prepend(data) : $(document).find('#custom_form_data_'+appendcount).after(data);
			}else{
				$('.custom_form_wrapper').append(data);
			}
			
			var value = '\
							<div class="custom_form_data_hidden_'+questioncount+'">\
								<input type="hidden" class="idhidden" value="'+id+'" name="questiondata['+questioncount+'][id]">\
								<input type="hidden" class="questionhidden" value="'+questionfield+'" name="questiondata['+questioncount+'][question]">\
								<input type="hidden" class="optionshidden" value="'+optionsfield+'" name="questiondata['+questioncount+'][options]">\
								'+choicehiddensection+'\
							</div>\
						';
			$('form#edit_form').append(value);
			
			clearfields();
			
			if(editflag!=''){
				questioncount = questioncountduplicate;
			}else{
				questioncount++
			}
		}
		
		$(document).on('click', '.removefield', function(e){
			var id = $(this).attr('data-id');
			$(document).find('.custom_form_data_hidden_'+id).remove();
			$(this).parent().parent().remove();
		})
		
		$(document).on('click', '.editfield', function(e){
			
			clearfields();
			
			var id 				= $(this).attr('data-id');
			var hiddenfields 	= $('.custom_form_data_hidden_'+id);
			
			$('.idfield').val(hiddenfields.find('.idhidden').val());
			$('.editflagfield').val(id);
			$('.questionfield').val(hiddenfields.find('.questionhidden').val());
			$('.optionsfield').val(hiddenfields.find('.optionshidden').val());
			
			var options 		= $('.optionsfield').val();
			optiontoggle(options, 1);
			
			hiddenfields.find('input[class="keyhidden"]').each(function(i, v){
				var image = (options==4) ? filepath+hiddenfields.find('.valuehidden').eq(i).val() : '';
				choicesfield($(this).val(), hiddenfields.find('.valuehidden').eq(i).val(), image);
			})
			
			$('.addfield').val('UPDATE');
			
			$('html, body').animate({
				scrollTop: $(document).find('.custom_form').offset().top
			}, 500);
		})
		
		function clearfields(){
			$('.idfield, .editflagfield, .questionfield, .optionsfield').val('');
			$('.choice_box').hide();
			$('.choicesrow').remove();
			
			$('.addfield').val('ADD');
		}
	});
</script>